#!/usr/bin/env python3
"""Claude Code の会話ログ（JSONL）を読むための共通パーサー。

claude_log_map.py（地図づくり）と claude_log_extract.py（本文抽出）の両方から使う。
パースの仕様が1か所にしか無いようにするためのモジュールで、単体では何もしない。

ログの形式:

    ~/.claude/projects/<パスをハイフンに潰したプロジェクト名>/<セッションUUID>.jsonl
    ~/.claude/projects/<同上>/<セッションUUID>/subagents/agent-*.jsonl

  - 1行1レコードの JSONL。`type` に user / assistant / attachment / system など17種が入る
  - 外部脳として要るのは **オーナー本人が打った発言だけ**。実測ではログ全体 212MB のうち
    本人の発言は 86KB（0.04%）しかなく、残りはツール出力と運用系レコード

本人の発言だけを残すために、次の4段階で捨てる（件数は 2026-08-26 時点の実測）。

  1. `type` が "user" 以外 …………………………… 本人以外の行（assistant / attachment ほか）
  2. `isSidechain` が真 ……………………… 1,326件。サブエージェントへの指示。書いたのは Claude
  3. `isMeta` が真 ………………………………… 1,810件。環境情報などの運用系
  4. content に tool_result ブロック ……… 14,094件。ツールの実行結果。容量の大半はこれ

そのうえで、本文に混ざる運用系のタグ（スラッシュコマンドの展開、system-reminder、
タスク通知など）を取り除く。**レコードごと捨てずにタグ部分だけ削る**のは、
1つのレコードに本人の発言と system-reminder が同居する場合があり、
丸ごと捨てると本人の言葉まで失うため。削った結果が空になったものだけを捨てる。
"""
import os
import re
import json
import glob

LOG_ROOT = os.path.expanduser("~/.claude/projects")

# 本文に紛れ込む運用系のブロック。Claude Code が自動で差し込むもので、本人が打った文字ではない。
NOISE_BLOCK_RE = re.compile(
    r"<(system-reminder|ide_selection|ide_opened_file|local-command-stdout"
    r"|local-command-caveat|command-name|command-message|command-args"
    r"|task-notification|bash-input|bash-stdout|bash-stderr"
    r"|pr-created|create-pr-command|cu_window_hints)>.*?</\1>",
    re.DOTALL,
)
# 閉じタグを伴わずに現れる運用系の行。
NOISE_LINE_RE = re.compile(
    r"^\s*(\[Request interrupted.*?\]"
    r"|Caveat: The messages below were generated by the user.*?)\s*$",
    re.MULTILINE,
)


class Utterance:
    """オーナーの発言1件。"""

    __slots__ = ("date", "timestamp", "text")

    def __init__(self, date, timestamp, text):
        self.date = date            # "2026-08-26"
        self.timestamp = timestamp  # ISO8601 のまま
        self.text = text            # 運用系タグを取り除いた本文

    def __repr__(self):
        return f"<{self.date} {self.text[:20]}...>"


class Session:
    """1セッション（= JSONL 1ファイル）ぶんの発言。"""

    __slots__ = ("path", "project", "session_id", "title", "utterances")

    def __init__(self, path, project, session_id, title, utterances):
        self.path = path
        self.project = project          # "BeerSalon"
        self.session_id = session_id    # ファイル名の UUID
        self.title = title              # ai-title があればそれ、無ければ初回発言の冒頭
        self.utterances = utterances

    @property
    def date(self):
        """セッションの日付（最初の発言の日）。"""
        return self.utterances[0].date if self.utterances else ""

    @property
    def chars(self):
        return sum(len(u.text) for u in self.utterances)

    @property
    def longest(self):
        """いちばん長い発言の文字数。濃いセッションを選ぶ物差しに使う。"""
        return max((len(u.text) for u in self.utterances), default=0)


def strip_noise(text):
    """本文から運用系のタグ・行を取り除く。"""
    text = NOISE_BLOCK_RE.sub("", text)
    text = NOISE_LINE_RE.sub("", text)
    return text.strip()


def _content_text(message):
    """user レコードの content から本人の打った文字列を取り出す。

    tool_result ブロックを含むものはツールの実行結果なので None を返して捨てさせる。
    """
    content = (message or {}).get("content")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        blocks = [b for b in content if isinstance(b, dict)]
        if any(b.get("type") == "tool_result" for b in blocks):
            return None
        # image ブロックは本文が無いので text だけ拾う。
        return "".join(b.get("text", "") for b in blocks if b.get("type") == "text")
    return None


def project_name(record, path):
    """プロジェクト名を決める。

    ディレクトリ名は `/` をハイフンに潰した形で、リポジトリ名にもハイフンが入りうるため
    元のパスへ復元できない。レコードの `cwd` があればそれを使い、無いときだけ
    ディレクトリ名の末尾で代用する。
    """
    cwd = record.get("cwd")
    if cwd:
        return os.path.basename(cwd.rstrip("/"))
    rel = os.path.relpath(path, LOG_ROOT)
    return rel.split(os.sep)[0].split("-")[-1]


def parse(path):
    """JSONL 1ファイルを読み、Session を返す（発言が1件も無ければ None）。"""
    utterances = []
    project = None
    ai_title = None

    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue  # 書き込み途中で切れた行。ログは追記型なので末尾に起こりうる

            rtype = record.get("type")
            if rtype == "ai-title":
                ai_title = record.get("aiTitle")
                continue
            if rtype != "user":
                continue
            if record.get("isSidechain") or record.get("isMeta"):
                continue

            text = _content_text(record.get("message"))
            if text is None:
                continue
            text = strip_noise(text)
            if not text:
                continue

            if project is None:
                project = project_name(record, path)
            timestamp = record.get("timestamp", "")
            utterances.append(Utterance(timestamp[:10], timestamp, text))

    if not utterances:
        return None

    title = ai_title or utterances[0].text.replace("\n", " ")[:40]
    session_id = os.path.basename(path).removesuffix(".jsonl")
    return Session(path, project or "?", session_id, title, utterances)


def iter_sessions(root=LOG_ROOT):
    """ログ配下の全 JSONL を走査し、発言のある Session だけを日付順で返す。"""
    sessions = []
    for path in sorted(glob.glob(os.path.join(root, "**", "*.jsonl"), recursive=True)):
        session = parse(path)
        if session:
            sessions.append(session)
    sessions.sort(key=lambda s: (s.date, s.project, s.session_id))
    return sessions
